check_data: false
full_mini: false
corpus: true
greedy: false
model_type: "rnn"
epochs: 5
lr: 0.0003
logdir: ""
batch_size: 4
hidden_dim: 128
test_sweep: false
lm_weight: 3.23
word_score: -0.26
sample_size: 0
d_model: 512
nhead: 8
dim_feedforward: 2048
nlayers: 6
lstm_hidden: 256
lstm_layers: 1
dropout: 0.5
sample_spect_folder: null
debug_sample: false
conv_layer: false
beam_width: 32
best: false