project: week5_sweep
name: week5_sweep
method: random
metric:
  name: val_wer
  goal: minimize
parameters:
  learning_rate: 
    values: [0.0001, 0.001, 0.0005]
  batch_size:
    values: [8, 16, 32, 64]
  hidden_dimension: 
    values: [32, 64, 128,256]
  epochs: 
    values: [5]
  model_type: 
    values: ["cnn", "rnn"]
  full_mini: 
    values: [True]