project: week9_sweep_a
name: week9_sweep_a
method: bayes
metric:
  name: val_wer
  goal: minimize
parameters:
  learning_rate: 
    values: [0.0001, 0.001, 0.0005]
  batch_size:
    values: [32]
  hidden_dimension: 
    values: [32, 64, 128, 256]
  epochs: 
    values: [5]
  model_type: 
    values: ["rnn"]
  full_mini: 
    values: [False]
  corpus: 
    values: [True]
  greedy: 
    values: [False]
  lm_weight:
    values: [0.5, 1.0, 2.0, 3.23]
  word_score: 
    values: [-0.52, -0.26, 0.0, 0.5]
  sample_size: 
    values: [32000]
  beam_width: 
    values: [16, 32, 48]
  best: 
    values: [True]
